name: Fuzz Test

on:
  push:
    branches: master

env:
  BUILD_TYPE: Release

jobs:
  fuzz-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install AFL++
      run: |
        sudo apt-get update
        sudo apt-get install -y afl++

    - name: Configure CMake
      run: CC=afl-clang-fast CXX=afl-clang-fast++ cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build with CMake
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Prepare Fuzzing Inputs
      run: |
        mkdir -p ${{github.workspace}}/fuzz_inputs
        echo "seed_input" > ${{github.workspace}}/fuzz_inputs/seed.txt

    - name: Run AFL++ Fuzzer
      env:
        AFL_I_DONT_CARE_ABOUT_MISSING_CRASHES: 1
      run: |
          afl-fuzz -i ${{github.workspace}}/fuzz_inputs -o ${{github.workspace}}/fuzz_outputs -- ${{github.workspace}}/build/PDFWriterTesting/PDFWriterTesting @@

    - name: Upload Fuzzing Outputs as Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: fuzz-outputs
        path: ${{github.workspace}}/fuzz_outputs/**