name: Fuzz Test

on:
  push:
    branches: tmp

env:
  BUILD_TYPE: Release

jobs:
  fuzz-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential clang llvm git

      - name: Install AFL++
        run: |
          mkdir -p ~/afl
          cd ~/afl
          git clone https://github.com/AFLplusplus/AFLplusplus
          cd AFLplusplus
          make distrib
          sudo make install

      - name: Configure CMake
        run: CC=~/afl/AFLplusplus/afl-clang-fast CXX=~/afl/AFLplusplus/afl-clang-fast++ cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build with CMake
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Run AFL++ Fuzzer with Workers
        env:
          AFL_I_DONT_CARE_ABOUT_MISSING_CRASHES: 0
        run: |
            afl-fuzz -M master -i ./PDFWriterTesting/Materials -o ./fuzz_outputs -t 5000 -- ./build/PDFWriterTesting/PDFWriterTesting ./PDFWriterTesting/Materials/ ./build/Testing/Output @@ &

            afl-fuzz -S worker1 -i ./PDFWriterTesting/Materials -o ./fuzz_outputs -t 5000 -- ./build/PDFWriterTesting/PDFWriterTesting ./PDFWriterTesting/Materials/ ./build/Testing/Output @@ &

            wait
      
      - name: Upload Fuzzing Outputs as Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: fuzz-outputs
          path: ${{github.workspace}}/fuzz_outputs/