name: Fuzz Test

on:
  push:
    branches: master

env:
  BUILD_TYPE: Release

jobs:
  fuzz-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install AFL++
      run: |
        sudo apt-get update
        sudo apt-get install -y afl++

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build with CMake
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: List Testing Directory Contents
      run: ls -l ${{github.workspace}}/build/Testing/Output

    - name: Prepare Fuzzing Inputs
      run: |
        mkdir -p ${{github.workspace}}/fuzz_inputs
        echo "seed_input" > ${{github.workspace}}/fuzz_inputs/seed.txt

    - name: Run AFL++ Fuzzer for Testing Binaries
      run: |
        export AFL_I_DONT_CARE_ABOUT_MISSING_CRASHES=1
        timestamp=$(date +%s)  # Get the current timestamp
        for binary in ${{github.workspace}}/build/Testing/Output/*; do
          if [ -x "$binary" ]; then
            fuzzer_id=$(basename "$binary")
            output_dir="${{github.workspace}}/fuzz_outputs/${fuzzer_id}_${timestamp}"
            mkdir -p "$output_dir"
            afl-fuzz -i ${{github.workspace}}/fuzz_inputs -o "$output_dir" -- "$binary" @@ &
          fi
        done
        wait

    - name: Upload Fuzzing Outputs as Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: fuzz-outputs
        path: ${{github.workspace}}/fuzz_outputs/**